### ISSUE TITLE
Cam ID

### ISSUE THREAD

**Issue by abeauvisage** [abeauvisage/uasl-image-acquisition#3]
Cam ID needs to be a string or char* for Tau2 to selected the correct camera.
Need to update camera_sequential, camera_mvbluefox, camera_tau2.

**Comment by HorseBatteryStapleCorrect** [comment]
Should be fixed with commit https://github.com/abeauvisage/uasl_image_acquisition/commit/c709210e721290342b496ef1a9674865ca68f180
