### ISSUE TITLE
Trigger class name

### ISSUE THREAD

**Issue by abeauvisage** [abeauvisage/uasl-image-acquisition#4]
What VCP means in the class name? Is it still valid if trigger is different from the trinket board?
port and Baudrate shouldn't be hard coded, won't be always the same.

**Comment by HorseBatteryStapleCorrect** [comment]
The VCP stands for Virtual COM Port. If I remember right, the trigger is accessed via the VCP driver (http://www.ftdichip.com/Drivers/VCP.htm) which simulates a COM port. If the trigger is different, then it depends what protocol of communication is used. If this is a COM port as well, then I guess specifiyng the right port and baudrate would allow it to work. The baudrate and port name are currently default values hardcoded in the trigger.hpp, it would certainly be possible to put them as parameters in a new constructor.

**Comment by abeauvisage** [comment]
Ok so no need to change the name, I'll change the parameters when I'll work with the trigger.
