### ISSUE TITLE
trigger Input

### ISSUE THREAD

**Issue by abeauvisage** [abeauvisage/uasl-image-acquisition#6]
Need for a BlueFOX param to select the camera Input In0/In1. It is hard coded for now.

**Comment by HorseBatteryStapleCorrect** [comment]
Is it about the trigger input ? Last time we tested it, only one of the two input would actually work, the other one would result in a terribly distorted image, which is why we hardcoded it that way. Does it work for both input on your camera ?

**Comment by abeauvisage** [comment]
I haven't tried both as I have only In0 connected and it took me some time wondering why it wasn't trigger before realising the wrong input was selected by default in the camera class itself, so I think it would be nice to have it as an option, this way you can easily change between inputs if one is no suitable. With ICG200w I didn't get any distortion or problem of any kind.

**Comment by HorseBatteryStapleCorrect** [comment]
Should be fixed with commit e6f499fd6a57e6649719aff0e7460ea5d5d40d5c
